### ISSUE TITLE
Insert Youtube link to the readme.md

### ISSUE THREAD

**Issue by igavronski** [christoomey/your-first-vim-plugin#2]
Hi,

I would suggest that you add the link for your youtube talk (watch?v=lwD8G1P52Sk) to the readme.md.

Regards.

**Comment by christoomey** [comment]
A fine idea indeed! Added in https://github.com/christoomey/your-first-vim-plugin/commit/afcabc0e801040ef41bc8394d934371b42d6ec3e. Thanks!
