### ISSUE TITLE
MoveEn crashes if there is no blank line before

### ISSUE THREAD

**Issue by voyeg3r** [christoomey/your-first-vim-plugin#3]
I have created I lightly different version in order to get your opinion on it
https://gist.github.com/voyeg3r/cfbcafba410259ceb7362397788dd6a4

If we use: let previous_blank_line = search('^$', 'bn')  in a block of text that does not have previous blank line it will set previous_blank_line to another place

So I tried something different
keepjumps execute 'normal {'
  if getline('.') !~ '^$'
    let previous_blank_line = line('.') - 1
  else
    let previous_blank_line = line('.')
endif

**Comment by christoomey** [comment]
Looks good to me! It's been a few years since I've touched any of this, but the issue you're describing makes sense, as does your solution 👍
